apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot-deficiente
  namespace: telegrambot-deficiente
spec:
  selector:
    matchLabels:
      app: telegrambot-deficiente
  replicas: 1
  template:
    metadata:
      labels:
        app: telegrambot-deficiente
    spec:
      containers:
        - name: telegrambot-deficiente
          image: ghcr.io/adrianvillanueva997/deficientebot_telegram:v0.6.0
          ports:
            - containerPort: 8080
          env:
            - name: TELOXIDE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-teloxide-token-telegrambot-deficiente
                  key: token
            - name: url
              value: "https://deficiente.thexiao77.com"
            - name: RUST_BACKTRACE
              value: "full"
            - name: RUST_LOG
              value: "info"
      restartPolicy: Always
