apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot-deficiente
  namespace: telegrambot-deficiente
spec:
  selector:
    matchLabels:
      app: telegrambot-deficiente
  replicas: 1
  template:
    metadata:
      labels:
        app: telegrambot-deficiente
    spec:
      containers:
        - name: telegrambot-deficiente-bot
          image: ghcr.io/adrianvillanueva997/deficientebot_telegram:v0.16.0
          ports:
            - containerPort: 8080
          env:
            - name: TELOXIDE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-teloxide-token-telegrambot-deficiente
                  key: token
            - name: url
              value: "https://deficiente.thexiao77.com"
            - name: RUST_BACKTRACE
              value: "full"
            - name: RUST_LOG
              value: "info"
            - name: "REDIS_URL"
              value: "redis://telegrambot-deficiente-redis:6379"
        - name: telegrambot-deficiente-redis
          image: redis:7.2.4-alpine
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: telegrambot-deficiente-redis-data
              mountPath: /data
      restartPolicy: Always
      volumes:
        - name: telegrambot-deficiente-redis-data
          persistentVolumeClaim:
            claimName: telegrambot-deficiente-redis-pvc
