apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ts3-ukranian-pvc
  namespace: ts3-ukranian
spec:
  storageClassName: ts3-ukranian-local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ts3-ukranian-local-storage
  namespace: ts3-ukranian
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ts3-ukranian-pv
  namespace: ts3-ukranian
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ts3-ukranian-local-storage
  local:
    path: /mnt/ts3-ukranian
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - vmi1572623.contaboserver.net
