apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: ts3-ingress-route-udp
  namespace: ts3-ukranian
spec:
  entryPoints:
    - ts3
  routes:
    - match: HostSNI(`ts3.thexiao77.com`)
      services:
        - name: ts3-ukranian
          port: 9987
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: ts3-ingress-tcp
  namespace: ts3-ukranian
spec:
  entryPoints:
    - ts3filetransfer
  routes:
    - match: HostSNI(`ts3.thexiao77.com`)
      services:
        - name: ts3-ukranian
          port: 30033
