apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-application
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    repoURL: https://github.com/adrianvillanueva997/kubernetes-deployments
    path: .
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: "argoproj.io"
      kind: "Application"
      jsonPointers:
        - /spec/source/targetRevision
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  project: default
  source:
    repoURL: https://github.com/adrianvillanueva997/kubernetes-deployments
    path: traefik
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  project: default
  source:
    repoURL: https://metallb.github.io/metallb
    targetRevision: v0.13.2
    chart: metallb
  destination:
    server: https://kubernetes.default.svc
    namespace: metallb # Specify the namespace where you want to install MetalLB
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
