apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appofapps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/adrianvillanueva997/kubernetes-deployments
    targetRevision: main
    path: . # Assuming your Kustomize configuration is in the root of your Git repository
    kustomize: {} # This line tells Argo CD to use Kustomize
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
