apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: meta-application
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-app-of-apps
  project: default
  source:
    repoURL: https://github.com/adrianvillanueva997/kubernetes-deployments
    path: meta-application/templates
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  ignoreDifferences:
    - group: "argoproj.io"
      kind: "Application"
      jsonPointers:
        - /spec/source/targetRevision
