---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-telegrambot-key-telegrambot-reminders
  namespace: telegrambot-reminders
spec:
  encryptedData:
    token: AgBufohILMXW4ZmbvK/mgqik11qQHZQt0FMhGIBF5NdNXLjomUj1Z6vIhxXMVqG1wSEHZenogNkqLJDxhsVf+5sSHHf2wwZGCg88atygXHyxyhfOl/MUNmEbNmeIBJp2jla+5iE1o7xVtjOHk70y8UQQ7qpti6iu3nv1PMvXfnqtXTz10brSMfQhyY++wVaU2YFczpgzIDIYMApSjGixhjqX7CeK/qww5BwqNHnX4mluN/EPGuGTlnqYU4AoVtbz/LtyMftYk0zorF8uiqsebom0W7brwdhnYhYV+uAcGjckyhxdpp6gl6GIO/VgTfVO7gTfbHn6cFjoMfqEAe6rhH+gw1qAPPuSM9AfjLDBRDBngdzC9i1le+IIJJmRhnqn/pf7A+XbWknEZBXB1b1BXNVuzLZxA6sfAaGnH7BVbUxxHSLRjrFHCrmMKW3pVOtLcj8qf+C/d+Uwo+ZXRlfXvyMfQdE8iY1UVd53wWurhbRunEAMgAuKkeBsHBWzCYDSXvZ30e8+aDWc1Yv6zoFG4X5/RC5XnyS/2fMI3hvNHXt15rzb2Dy5YMFyt6LMm1d9/w68mqDxibQqMo8w33I+CQ0XG+FzdHlHzUsNMY9pKCNsLadHfPdg42ilZf5ICD65hkJLAwmx2AQW2FGcl/tokemD3LXsqEipXIgi+1VBfv4Fkgf6fTxVRW99ts07mBNvOge7tE/eggrOs/R/I4VHUbdWBhA0NW26s053LG4gIHz3AEJuwIsriMSROQIk2ZCu
  template:
    metadata:
      creationTimestamp: null
      name: secret-telegrambot-key-telegrambot-reminders
      namespace: telegrambot-reminders
    type: Opaque
