apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nginx-lmao-letsencrypt-staging
  namespace: nginx-lmao
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: adrianvillanueva997@gmail.com
    privateKeySecretRef:
      name: nginx-lmao-staging
    solvers:
      - selector: {}
        http01:
          ingress:
            class: traefik

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: nginx-lmao-letsencrypt-production
  namespace: nginx-lmao
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adrianvillanueva997@gmail.com
    privateKeySecretRef:
      name: nginx-lmao-production
    solvers:
      - selector: {}
        http01:
          ingress:
            class: traefik
