apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-lmao-pvc
  namespace: nginx-lmao
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
