apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adrianvillanueva
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/adrianvillanueva997/adrianvillanueva.com
    path: infra
    targetRevision: master
  destination:
    server: https://kubernetes.default.svc
    namespace: adrianvillanueva
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
