# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: loki
#   finalizers:
#     - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/adrianvillanueva997/kubernetes-deployments
#     path: charts/loki
#     targetRevision: HEAD
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: loki
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true
#     syncOptions:
#       - CreateNamespace=true
