apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: telegrambot-deficiente
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/adrianvillanueva997/DeficienteBot_Telegram
    path: infra
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: telegrambot-deficiente
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
