apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 26.0.0
    helm:
      releaseName: traefik
      valueFiles:
        - values.yaml # Include the values.yaml file
      values: |
        api:
          insecure: true
          dashboard: true
        ports:
          minecraft:
            port: 25565
            expose: true
            exposedPort: 25565
            protocol: TCP
        additionalArguments:
          - "--providers.kubernetesingress.ingressclass=traefik"
          - "--providers.kubernetescrd.namespaces=_all"
        certificatesResolvers:
          myresolver:
            acme:
              email: your-email@example.com
              storage: acme.json
              httpChallenge:
                # used during the challenge
                entryPoint: web
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
---
