apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - traefik.yaml
  - traefik-dashboard.yaml
  - certificates.yaml

configMapGenerator:
  - name: traefik-config
    files:
      - values.yaml
