apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00traefik.yaml
  # - 02traefik-dashboard.yaml
  - 01certificates.yaml

configMapGenerator:
  - name: traefik-config
    files:
      - values.yaml
