apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 26.0.0
    helm:
      releaseName: traefik
      values: |
        api:
          insecure: true
          dashboard: true
        ports:
          minecraft:
            port: 25565
            expose: true
            exposedPort: 25565
            protocol: TCP
        additionalArguments:
          - "--providers.kubernetescrd.namespaces=traefik"
        certResolvers:
          letsencrypt:
            email: adrianvillanueva997@gmail.com
            dnsChallenge:
              # provider: digitalocean
              delayBeforeCheck: 30
              resolvers:
                - 1.1.1.1
                - 8.8.8.8
            tlsChallenge: true
            httpChallenge:
              entryPoint: web
            storage: /data/traefik/acme.json
            persistence:
              enabled: true
              accessMode: ReadWriteOnce
              path: /data/traefik/acme.json

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
