apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 26.0.0
    helm:
      releaseName: traefik
      values: |
        ports:
          minecraft:
            port: 25565
            expose: true
            exposedPort: 25565
            protocol: TCP
    # valuesFiles:
    #   - values.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
