api:
  insecure: true
  dashboard: true
ports:
  minecraft:
    port: 25565
    expose: true
    exposedPort: 25565
    protocol: TCP
additionalArguments:
  - "--providers.kubernetescrd.namespaces=traefik"
certificatesResolvers:
  myresolver:
    acme:
      email: your-email@example.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web
