traefik:
  ingressRoute:
    dashboard:
      enabled: true
      # Custom match rule with host domain
      matchRule: Host(`traefik.thexiao77.com`)
      entryPoints: ["web", "websecure"]
      middlewares:
        - name: auth-traefik-dashboard
          namespace: traefik
        - name: middleware-https-traefik-dashboard
          namespace: traefik
      tls:
        secretName: traefik-dashboard-tls
  # ports:
  #   minecraft:
  #     expose: true
  #     exposedPort: 25565
  #     protocol: TCP
  # additionalArguments:
  #   - "--entrypoints.minecraft.address=:25565/tcp"
