traefik:
  ingressRoute:
    dashboard:
      enabled: true
      # Custom match rule with host domain
      matchRule: Host(`test.thexiao77.com`)
      entryPoints: ["web", "websecure"]
      middlewares:
        - name: auth-traefik-dashboard
          namespace: traefik
        - name: https-redirect-middleware-traefik-dashboard
          namespace: traefik
      tls:
        secretName: traefik-dashboard-tls
