apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  project: default
  source:
    path: traefik
    repoURL: https://github.com/adrianvillanueva997/kubernetes-deployments
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
