apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik.yaml: |
    log:
      level: INFO
    api:
      insecure: true
    providers:
      kubernetesIngress: true
      kubernetesCRD: true
    entryPoints:
      http:
        address: :80
      https:
        address: :443
