apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
data:
  traefik-config.yaml: |
    api:
      dashboard: true
      insecure: true
    entryPoints:
      http:
        address: ":80"
      https:
        address: ":443"
