apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: traefik
spec:
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 2.10.7
    helm:
      releaseName: traefik
      valueFiles:
        - values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
