apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik.yaml: |
    api:
      dashboard: true
      insecure: true

    entryPoints:
      web:
        address: :80

    providers:
      kubernetesCRD: {}
