apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`argocd.thexiao77.com`)
      priority: 10
      services:
        - name: argocd-server
          port: 80
    - kind: Rule
      match: Host(`argocd.thexiao77.com`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: argocd-server
          port: 80
          scheme: h2c
  tls:
    secretName: argocd-web-ui-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-web-ui-tls
  namespace: traefik
spec:
  secretName: argocd-web-ui-tls
  issuerRef:
    name: argocd-letsencrypt-production
    kind: Issuer
  commonName: argocd.thexiao77.com
  dnsNames:
    - argocd.thexiao77.com
