apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: argocd-letsencrypt-staging
  namespace: argocd
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: adrianvillanueva997@gmail.com
    privateKeySecretRef:
      name: argocd-staging
    solvers:
      - selector: {}
        http01:
          ingress:
            class: traefik

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: argocd-letsencrypt-staging
  namespace: argocd
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adrianvillanueva997@gmail.com
    privateKeySecretRef:
      name: argocd-production
    solvers:
      - selector: {}
        http01:
          ingress:
            class: traefik
