apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certmanager
  namespace: argocd
spec:
  project: default
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  source:
    chart: cert-manager
    repoURL: https://charts.jetstack.io
    targetRevision: v1.13
    helm:
      releaseName: cert-manager
      values: |
        installCRDs: true
        prometheus:
          enabled: true
        webhook:
          enabled: true
        cainjector:
          enabled: true
        nodeSelector:
          kubernetes.io/os: linux
        tolerations:
          - key: node-role.kubernetes.io/master
            effect: NoSchedule
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - cert-manager
                topologyKey: kubernetes.io/hostname
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
