apiVersion: apps/v1
kind: Deployment
metadata:
  name: adrianvillanueva
  namespace: adrianvillanueva
spec:
  selector:
    matchLabels:
      app: adrianvillanueva
  replicas: 1
  template:
    metadata:
      labels:
        app: adrianvillanueva
    spec:
      containers:
        - name: adrianvillanueva
          image: ghcr.io/adrianvillanueva997/adrianvillanueva.com:v0.3.0@sha256:73f90db8f386a33fa4435ddf16976fd214dbaaca3aa908e54b5149ad2ff151f6
          ports:
            - containerPort: 8080

      restartPolicy: Always
