apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: adrianvillanueva.com-letsencrypt-staging
  namespace: adrianvillanueva.com
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: adrianvillanueva997@gmail.com
    privateKeySecretRef:
      name: adrianvillanueva.com-staging
    solvers:
      - selector: {}
        http01:
          ingress:
            class: traefik

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: adrianvillanueva.com-letsencrypt-production
  namespace: adrianvillanueva.com
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adrianvillanueva997@gmail.com
    privateKeySecretRef:
      name: adrianvillanueva.com-production
    solvers:
      - selector: {}
        http01:
          ingress:
            class: traefik
