apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot-ukranian
  namespace: telegrambot-ukranian
spec:
  selector:
    matchLabels:
      app: telegrambot-ukranian
  replicas: 1
  template:
    metadata:
      labels:
        app: telegrambot-ukranian
    spec:
      containers:
        - name: telegrambot-ukranian
          image: ghcr.io/adrianvillanueva997/telegrambot-ukranian:v4.0.0@sha256:30c127f0413ebbfba9eb92f4a7356bd5e99df12f3d4d8a823125a21a444a27e1
          ports:
            - containerPort: 8080
          env:
            - name: TELOXIDE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-teloxide-key-telegrambot-ukranian
                  key: token
            - name: openweather_key
              valueFrom:
                secretKeyRef:
                  name: secret-openweather-key-telegrambot-ukranian
                  key: token
            - name: url
              value: "https://ukranian.thexiao77.com"
            - name: RUST_BACKTRACE
              value: "full"
            - name: RUST_LOG
              value: "info"
      restartPolicy: Always
