apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot-ukranian
  namespace: telegrambot-ukranian
spec:
  selector:
    matchLabels:
      app: telegrambot-ukranian
  replicas: 1
  template:
    metadata:
      labels:
        app: telegrambot-ukranian
    spec:
      containers:
        - name: telegrambot-ukranian
          image: ghcr.io/adrianvillanueva997/telegrambot-ukranian:v3.0.0@sha256:6971a444ed03cb3b15a431ebad88f3f3a15fe25a3b80258249a118cc478653d5
          ports:
            - containerPort: 8080
          env:
            - name: TELOXIDE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: secret-teloxide-key-telegrambot-ukranian
                  key: token
            - name: openweather_key
              valueFrom:
                secretKeyRef:
                  name: secret-openweather-key-telegrambot-ukranian
                  key: token
            - name: url
              value: "https://ukranian.thexiao77.com"
            - name: RUST_BACKTRACE
              value: "full"
            - name: RUST_LOG
              value: "info"
      restartPolicy: Always
