cert-manager:
  installCRDs: true
  prometheus:
    enabled: true
  webhook:
    enabled: true
  cainjector:
    enabled: true
  nodeSelector:
    kubernetes.io/os: linux
  tolerations:
    - key: node-role.kubernetes.io/master
      effect: NoSchedule
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: app
                operator: In
                values:
                  - cert-manager
          topologyKey: kubernetes.io/hostname
