apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: https-redirect-middleware-traefik-dashboard
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
    permanent: true

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-dashboard-certificate
  namespace: traefik
spec:
  secretName: traefik-dashboard-tls
  issuerRef:
    name: letsencrypt-production
    kind: Issuer
  commonName: test.thexiao77.com
  dnsNames:
    - test.thexiao77.com

---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: auth-traefik-dashboard
  namespace: traefik
spec:
  basicAuth:
    secret: secret-auth-traefik-dashboard
