apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-auth-traefik-dashboard
  namespace: traefik
spec:
  encryptedData:
    users: AgCwCmSvks2E3Cttqy3U7L4FnB7iC5wJlJEiHIhvAhI7kU03b1Xqk1izn/6N6rmtoSvAuFJs5Nh6xwqbDa5S+lYCU9o5qB2vqyP0jFa2hmtO6zA8Eb82ZAnMBX0G8jgmxIcj2A5uRuqLRI1S0y2B3UxrmO5is7xVTklYuoPwV+kyWnGQU5sfsorazT0rwKYVE49gFHqDcXI+M3/2cXpD06Y9rzuSn/0pgxVQYb3RQ0+Iji+Wy8R7XB1HcpLg9a0cDFx0n2tn0o7wAJFogZjq3YNWYwnsIUHatXeZAv7vmJ6kgNsFjIqaICMz2FEt5U94J+ftdO4wEW0kO8DqZTMrvL+uqLkFHvGgTC4QBU/S65pvGiXhuTHGg+5YJWOGZmLNXDTz+HA0YhktR8j8tKMKu91OBxplHpZDXlFnsuP6JG8S9rI36OAHt2zv1FZPCTYAoJs17KqRitGnlNyzRUQnKXZqzr9DJdbNh0cBNlCmt3UgCNAxounm4gFrwlUsjiqvOk8TFxCrpwwLC85VsTorSJCJqf9LZ2GpVsrveZROoVrX4Y7kX/j7BJDYm7gstatswAP2qtxHwdbidwZTFwC2yEzsOZTfXtRH8enx3q+T0pb0clsEGt7d/2S+3L1U7vY6ouQaJmd4FnOL57BoQN/K3h70lORm7HdEO2BvZRHhnHf2sNTgobdCSOu6nDYXn9Nheuh/GwhNvu1zSgiwT+zy+4HhcKaTlxnbiu1QYM/9ZllYRaQBm6szoSdTrN6haw==
  template:
    metadata:
      creationTimestamp: null
      name: secret-auth-traefik-dashboard
      namespace: traefik
    type: Opaque
