apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: default
  destination:
    namespace: metallb
    server: https://kubernetes.default.svc
  source:
    chart: metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.12
    helm:
      releaseName: metallb
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
---
apiVersion: metallb.io/v2alpha1
kind: IPAddressPool
metadata:
  namespace: metallb
  name: default
spec:
  addresses:
    - 167.86.69.118/32
  protocol: layer2
