# metallb-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: metallb-system
  name: speaker
spec:
  selector:
    matchLabels:
      name: speaker
  template:
    metadata:
      labels:
        name: speaker
    spec:
      hostNetwork: true
      containers:
        - name: speaker
          image: bitnami/metallb-speaker:v0.11.0
