apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: helm/metallb
    repoURL: https://metallb.github.io/metallb
    targetRevision: 0.13.12
  syncPolicy:
    automated: {}
