apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio
  namespace: minio
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/minio"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
  namespace: minio
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
